//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lxsh.Project.WcfClient.Lxsh.WcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Lxsh.WcfService.IEventAlarm", CallbackContract=typeof(Lxsh.WcfService.IEventAlarmCallback))]
    public interface IEventAlarm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventAlarm/Login", ReplyAction="http://tempuri.org/IEventAlarm/LoginResponse")]
        void Login(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventAlarm/Login", ReplyAction="http://tempuri.org/IEventAlarm/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventAlarmCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventAlarm/Notify1", ReplyAction="http://tempuri.org/IEventAlarm/Notify1Response")]
        void Notify1(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventAlarm/Notify2", ReplyAction="http://tempuri.org/IEventAlarm/Notify2Response")]
        void Notify2(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventAlarmChannel : Lxsh.WcfService.IEventAlarm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventAlarmClient : System.ServiceModel.DuplexClientBase<Lxsh.WcfService.IEventAlarm>,Lxsh.WcfService.IEventAlarm {
        
        public EventAlarmClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public EventAlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public EventAlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EventAlarmClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EventAlarmClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(string username) {
            base.Channel.Login(username);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string username) {
            return base.Channel.LoginAsync(username);
        }
    }
}
